using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using SakuraHomeAPI.Models.Base;

namespace SakuraHomeAPI.Models.Entities.Orders
{
    /// <summary>
    /// Order notes for internal communication
    /// </summary>
    [Table("OrderNotes")]
    public class OrderNote : AuditableEntity
    {
        public int OrderId { get; set; }

        [Required]
        public string Note { get; set; }

        public bool IsPublic { get; set; } = false; // Visible to customer
        public bool IsSystem { get; set; } = false; // Generated by system

        public virtual Order Order { get; set; }
    }
}
